services:
  app:
    # Если нужно сбилдить локально
    # build: .
    image: temirlant201/async-fastapi-processor:latest  # заменили build на image
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
